import {
  runChapterRule,
  type ChapterEventTemplate,
  type ChapterRuleModule,
  type ChapterSimulationInput,
} from '../chapterSimulation'

const started = (detail: string): ChapterEventTemplate => ({
  atMs: 0,
  kind: 'experiment.started',
  component: 'producer',
  state: 'active',
  title: '배송 규칙을 적용한다',
  detail,
  log: `[producer] ${detail}`,
})

export const chapter2Rule = {
  chapterId: 2,
  experiments: [
    {
      id: 'same-key-same-partition',
      title: '같은 고객의 주문 경로',
      mission: '같은 고객의 이벤트가 한 partition 안에서 기록 순서를 유지하도록 key를 설계한다.',
      predictionPrompt: '세 주문에 서로 다른 임의 key를 붙이면 어떤 partition에 기록될까?',
      successCriteria: '동일한 업무 key가 같은 partition과 증가하는 offset으로 이어진다.',
      recommendedChoiceId: 'stable-customer-key',
      referenceIds: ['kafka-introduction', 'producer-configs'],
      choices: [
        {
          id: 'random-key-per-record',
          label: '매번 임의 key 사용',
          description: '같은 고객의 주문에도 전송할 때마다 새로운 UUID key를 붙인다.',
          outcome: {
            status: 'failed',
            summary: '업무상 같은 고객의 이벤트가 서로 다른 partition으로 갈라져 순서 단위를 잃었다.',
            events: [
              started('customer-42 주문 세 건에 매번 다른 UUID key를 지정'),
              {
                atMs: 140,
                kind: 'configuration.applied',
                component: 'producer',
                state: 'complete',
                title: '서로 다른 key가 직렬화됐다',
                detail: 'order-created, order-paid, order-shipped가 각각 uuid-a, uuid-b, uuid-c를 사용한다.',
                log: '[producer] keys=[uuid-a, uuid-b, uuid-c]',
              },
              {
                atMs: 280,
                kind: 'record.dispatched',
                component: 'partition',
                state: 'active',
                title: 'partition 선택 결과가 갈라졌다',
                detail: '기본 key 기반 선택에서 서로 다른 key 해시는 같은 partition을 보장하지 않는다.',
                log: '[partitioner] uuid-a->p0, uuid-b->p2, uuid-c->p1',
              },
              {
                atMs: 420,
                kind: 'evidence.observed',
                component: 'partition',
                state: 'blocked',
                title: 'offset만으로 고객 순서를 복원할 수 없다',
                detail: 'p0@18, p2@7, p1@31은 서로 비교 가능한 전역 offset이 아니다.',
                log: '[evidence] records span p0@18, p2@7, p1@31',
              },
              {
                atMs: 560,
                kind: 'experiment.failed',
                component: 'application',
                state: 'failed',
                title: '업무 ordering key가 불안정하다',
                detail: '같은 고객을 표현하는 안정적인 key가 필요하다.',
                log: '[result] customer-local ordering boundary was lost',
              },
            ],
            diagnosis: {
              symptom: '같은 고객의 주문 상태가 여러 partition에 흩어졌다.',
              rootCause: '레코드마다 다른 key를 사용해 partition 선택의 동일성 조건을 없앴다.',
              evidence: ['uuid-a→p0', 'uuid-b→p2', 'uuid-c→p1', 'partition 간 offset은 비교할 수 없음'],
              recommendedChoiceId: 'stable-customer-key',
              tradeOff: '고객별 순서를 얻는 대신 특정 고객 key에 트래픽이 몰리면 partition 편향이 생길 수 있다.',
            },
          },
        },
        {
          id: 'stable-customer-key',
          label: 'customerId를 key로 사용',
          description: '세 주문 모두 안정적인 업무 식별자 customer-42를 key로 사용한다.',
          outcome: {
            status: 'succeeded',
            summary: '동일 key가 같은 partition에 배치되고 그 partition의 offset 순서로 기록됐다.',
            events: [
              started('customer-42 주문 세 건에 동일한 customerId key를 지정'),
              {
                atMs: 140,
                kind: 'configuration.applied',
                component: 'producer',
                state: 'complete',
                title: '안정적인 업무 key가 적용됐다',
                detail: 'partition 수와 partitioner가 유지되는 동안 동일 key의 선택 결과가 안정적이다.',
                log: '[producer] key=customer-42 for 3 records',
              },
              {
                atMs: 280,
                kind: 'record.dispatched',
                component: 'partition',
                state: 'active',
                title: '세 레코드가 p1로 향한다',
                detail: '동일 key의 직렬화 바이트가 동일 partition 선택을 만든다.',
                log: '[partitioner] customer-42 -> p1 (x3)',
              },
              {
                atMs: 420,
                kind: 'evidence.observed',
                component: 'partition',
                state: 'complete',
                title: 'partition 내부 offset이 증가한다',
                detail: 'created, paid, shipped가 p1@31, p1@32, p1@33에 기록됐다.',
                log: '[broker] p1 offsets=[31,32,33]',
              },
              {
                atMs: 560,
                kind: 'experiment.succeeded',
                component: 'application',
                state: 'complete',
                title: '고객별 순서 경계가 만들어졌다',
                detail: '보장은 고객 key가 선택한 단일 topic-partition 안으로 한정된다.',
                log: '[result] customer-42 ordering is partition-local',
              },
            ],
            diagnosis: null,
          },
        },
      ],
    },
    {
      id: 'keyless-distribution',
      title: 'key 없는 주문의 분산',
      mission: '업무상 순서가 필요한 이벤트와 처리량을 위해 분산할 이벤트의 key 전략을 구분한다.',
      predictionPrompt: 'key=null 레코드도 같은 고객이면 자동으로 같은 partition에 머물까?',
      successCriteria: 'key 없음은 업무 ordering 단위가 아니며, 필요한 경우 명시적인 key를 선택한다.',
      recommendedChoiceId: 'restore-business-key',
      referenceIds: ['producer-configs'],
      choices: [
        {
          id: 'omit-key-and-assume-order',
          label: 'key 없이 순서를 가정',
          description: 'key를 생략한 뒤 배치가 언제나 같은 partition으로 갈 것이라 가정한다.',
          outcome: {
            status: 'failed',
            summary: 'key 없는 전송의 분산 동작을 고객별 ordering 계약으로 오해했다.',
            events: [
              started('customer-77 이벤트 네 건을 key=null로 전송'),
              {
                atMs: 120,
                kind: 'configuration.applied',
                component: 'producer',
                state: 'complete',
                title: '업무 key가 제거됐다',
                detail: 'partitioner에는 고객을 식별할 key 바이트가 전달되지 않는다.',
                log: '[producer] key=null, batch.size=16384, linger.ms=5',
              },
              {
                atMs: 260,
                kind: 'record.dispatched',
                component: 'partition',
                state: 'active',
                title: '배치 경계 뒤 선택이 바뀌었다',
                detail: '첫 배치는 p0, 다음 배치는 p2로 분산됐다.',
                log: '[partitioner] null-key batch#1->p0, batch#2->p2',
              },
              {
                atMs: 390,
                kind: 'evidence.observed',
                component: 'partition',
                state: 'blocked',
                title: '고객별 단일 로그가 없다',
                detail: 'p0과 p2는 각각 순서가 있지만 둘 사이의 전역 기록 순서는 보장되지 않는다.',
                log: '[evidence] customer-77 spans p0 and p2',
              },
              {
                atMs: 520,
                kind: 'experiment.failed',
                component: 'application',
                state: 'failed',
                title: 'keyless 분산을 ordering으로 사용할 수 없다',
                detail: '업무 순서가 필요하면 그 단위를 나타내는 key를 명시해야 한다.',
                log: '[result] no business ordering key',
              },
            ],
            diagnosis: {
              symptom: '한 고객의 이벤트가 배치 경계 이후 다른 partition에서 발견됐다.',
              rootCause: 'key가 없는 레코드의 분산 특성을 안정적인 고객별 partition 계약으로 간주했다.',
              evidence: ['batch#1→p0', 'batch#2→p2', 'p0과 p2 사이에는 전역 offset이 없음'],
              recommendedChoiceId: 'restore-business-key',
              tradeOff: 'keyless 분산은 부하 분산에 유리할 수 있지만 업무 엔터티별 순서 보장은 포기한다.',
            },
          },
        },
        {
          id: 'restore-business-key',
          label: 'ordering 단위에 key 부여',
          description: '고객별 순서가 필요한 레코드에 customerId key를 복원한다.',
          outcome: {
            status: 'succeeded',
            summary: '분산 목적과 ordering 목적을 구분하고 고객별 이벤트를 단일 partition에 모았다.',
            events: [
              started('순서가 필요한 customer-77 이벤트를 분류'),
              {
                atMs: 120,
                kind: 'configuration.applied',
                component: 'producer',
                state: 'complete',
                title: 'customerId key를 복원했다',
                detail: '순서 불필요 telemetry는 keyless, 주문 상태는 customerId key를 사용한다.',
                log: '[producer] order.key=customer-77; telemetry.key=null',
              },
              {
                atMs: 260,
                kind: 'record.dispatched',
                component: 'partition',
                state: 'active',
                title: '주문 이벤트가 p2로 모인다',
                detail: '동일 customerId가 한 partition 선택을 공유한다.',
                log: '[partitioner] customer-77 -> p2 (x4)',
              },
              {
                atMs: 390,
                kind: 'evidence.observed',
                component: 'partition',
                state: 'complete',
                title: 'p2 offset이 업무 순서를 증명한다',
                detail: '주문 상태가 p2@50부터 p2@53까지 연속으로 관찰된다.',
                log: '[evidence] p2 offsets=50..53',
              },
              {
                atMs: 520,
                kind: 'experiment.succeeded',
                component: 'application',
                state: 'complete',
                title: '분산과 순서의 의도가 분리됐다',
                detail: 'key 전략이 레코드 종류별 업무 요구를 표현한다.',
                log: '[result] explicit ordering boundary restored',
              },
            ],
            diagnosis: null,
          },
        },
      ],
    },
    {
      id: 'cross-partition-order',
      title: '도시 전체 순서의 착시',
      mission: 'Kafka의 기록 순서 보장 범위를 topic 전체가 아닌 topic-partition으로 설명한다.',
      predictionPrompt: 'p0@104와 p1@87 중 어느 이벤트가 topic 전체에서 먼저 기록됐다고 말할 수 있을까?',
      successCriteria: 'partition별 순서는 설명하되, 별도 합의 없이 전역 순서를 주장하지 않는다.',
      recommendedChoiceId: 'partition-local-timeline',
      referenceIds: ['kafka-introduction'],
      choices: [
        {
          id: 'sort-offsets-globally',
          label: 'offset을 전역 정렬',
          description: 'partition을 무시하고 숫자가 작은 offset을 더 이른 이벤트로 처리한다.',
          outcome: {
            status: 'failed',
            summary: '서로 독립적인 partition offset을 비교해 존재하지 않는 topic 전역 순서를 만들었다.',
            events: [
              started('p0과 p1에서 동시에 들어온 배송 이벤트를 병합'),
              {
                atMs: 130,
                kind: 'record.dispatched',
                component: 'partition',
                state: 'active',
                title: '두 partition에 독립적으로 append됐다',
                detail: '서부 배송은 p0@104, 동부 배송은 p1@87에 기록됐다.',
                log: '[broker] west=p0@104; east=p1@87',
              },
              {
                atMs: 270,
                kind: 'state.changed',
                component: 'application',
                state: 'active',
                title: 'offset 숫자만으로 병합했다',
                detail: '87이 104보다 작다는 이유로 동부 이벤트를 전역 선행으로 판정했다.',
                log: '[merge] sortBy(offset): p1@87 before p0@104',
              },
              {
                atMs: 410,
                kind: 'evidence.observed',
                component: 'partition',
                state: 'blocked',
                title: 'offset의 비교 범위가 다르다',
                detail: '각 offset은 해당 partition 로그에서만 위치를 나타낸다.',
                log: '[evidence] offset identity=(topic, partition, offset)',
              },
              {
                atMs: 540,
                kind: 'experiment.failed',
                component: 'application',
                state: 'failed',
                title: '거짓 전역 순서가 생성됐다',
                detail: 'partition 간 causal order가 필요하면 별도의 key 설계나 순서 메타데이터가 필요하다.',
                log: '[result] cross-partition order is undefined',
              },
            ],
            diagnosis: {
              symptom: 'offset 숫자 정렬이 실제 업무 선후 관계와 다른 결과를 냈다.',
              rootCause: 'partition마다 독립적으로 증가하는 offset을 topic 전체의 공통 좌표로 오해했다.',
              evidence: ['west=p0@104', 'east=p1@87', 'offset identity에는 partition이 포함됨'],
              recommendedChoiceId: 'partition-local-timeline',
              tradeOff: '전역 순서가 꼭 필요하면 단일 partition으로 모아 처리량을 제한하거나 애플리케이션 수준 순서 체계를 추가해야 한다.',
            },
          },
        },
        {
          id: 'partition-local-timeline',
          label: 'partition별 timeline 유지',
          description: '각 partition의 offset 순서만 주장하고 전역 병합에는 업무 timestamp와 규칙을 명시한다.',
          outcome: {
            status: 'succeeded',
            summary: 'partition별 ordering 증거와 애플리케이션 병합 규칙을 명확히 분리했다.',
            events: [
              started('배송 이벤트의 partition별 timeline을 구성'),
              {
                atMs: 130,
                kind: 'record.dispatched',
                component: 'partition',
                state: 'active',
                title: '각 로그를 독립적으로 읽었다',
                detail: 'p0@103→p0@104와 p1@86→p1@87의 로컬 선후만 확정한다.',
                log: '[broker] p0:103<104; p1:86<87',
              },
              {
                atMs: 270,
                kind: 'configuration.applied',
                component: 'application',
                state: 'complete',
                title: '병합 규칙을 별도로 선언했다',
                detail: '표시용 timeline은 eventTime과 동률 처리 규칙을 사용하며 Kafka 보장과 구분한다.',
                log: '[merge] display-only order=eventTime,eventId',
              },
              {
                atMs: 410,
                kind: 'evidence.observed',
                component: 'partition',
                state: 'complete',
                title: '보장 범위가 표시됐다',
                detail: '각 항목에 topic-partition-offset을 함께 노출한다.',
                log: '[evidence] coordinates include topic/partition/offset',
              },
              {
                atMs: 540,
                kind: 'experiment.succeeded',
                component: 'application',
                state: 'complete',
                title: '전역 순서의 착시를 제거했다',
                detail: 'Kafka의 순서 보장과 애플리케이션의 표시 규칙이 분리됐다.',
                log: '[result] partition-local guarantee documented',
              },
            ],
            diagnosis: null,
          },
        },
      ],
    },
  ],
} satisfies ChapterRuleModule

export function runChapter2Rule(input: ChapterSimulationInput) {
  return runChapterRule(chapter2Rule, input)
}
