import type { ChapterRuleModule } from '../chapterSimulation'

export const chapter4Rule: ChapterRuleModule = {
  chapterId: 4,
  experiments: [
    {
      id: 'replica-lag',
      title: '느려진 follower와 ISR',
      mission: 'replication factor와 현재 쓰기 성공에 참여하는 ISR을 구분한다.',
      predictionPrompt: 'replica 한 대가 따라오지 못하면 acks=all은 누구의 ACK를 기다릴까?',
      successCriteria: 'replica 수와 ISR 수를 별도의 상태로 설명한다.',
      recommendedChoiceId: 'inspect-current-isr',
      referenceIds: ['kafka-introduction', 'topic-configs'],
      choices: [
        {
          id: 'trust-replication-factor',
          label: 'replication factor만 확인한다',
          description: 'replica가 세 개이므로 세 복제본이 모두 최신이라고 가정한다.',
          outcome: {
            status: 'failed',
            summary: 'replication factor 3은 배치된 replica 수일 뿐, 현재 ISR이 2라는 사실을 숨겼습니다.',
            events: [
              {
                atMs: 0,
                kind: 'experiment.started',
                component: 'replica',
                state: 'active',
                title: 'replica 상태 확인 시작',
                detail: 'leader 1대와 follower 2대가 배치되어 있습니다.',
                log: 'partition=orders-0 replication.factor=3 leader=broker-1',
              },
              {
                atMs: 400,
                kind: 'state.changed',
                component: 'replica',
                state: 'blocked',
                title: '느린 follower가 ISR에서 제외됨',
                detail: 'broker-3은 replica로 남아 있지만 leader의 끝 offset을 제때 따라오지 못합니다.',
                log: 'partition=orders-0 replicas=[1,2,3] isr=[1,2] lagging=broker-3',
              },
              {
                atMs: 800,
                kind: 'experiment.failed',
                component: 'replica',
                state: 'failed',
                title: 'replica와 ISR을 같은 값으로 판단함',
                detail: '현재 쓰기 성공 조건은 고정 replica 수가 아니라 현재 ISR과 min.insync.replicas에 좌우됩니다.',
                log: 'diagnosis=replica-count-does-not-equal-current-isr',
              },
            ],
            diagnosis: {
              symptom: '세 replica가 모두 쓰기 성공에 참여한다고 예측했습니다.',
              rootCause: 'replication factor와 현재 동기화된 replica 집합인 ISR을 구분하지 않았습니다.',
              evidence: ['replicas=[1,2,3]', 'isr=[1,2]', 'broker-3 replica lag 감지'],
              recommendedChoiceId: 'inspect-current-isr',
              tradeOff: 'lagging replica를 ISR에서 제외하면 가용성 판단은 정확해지지만 장애 허용 여유는 줄어듭니다.',
            },
          },
        },
        {
          id: 'inspect-current-isr',
          label: 'replica와 ISR을 함께 확인한다',
          description: '배치된 replica와 현재 동기화된 ISR을 별도로 관찰한다.',
          outcome: {
            status: 'succeeded',
            summary: 'replica 3대 중 현재 ISR은 2대라는 상태를 정확히 구분했습니다.',
            events: [
              {
                atMs: 0,
                kind: 'experiment.started',
                component: 'replica',
                state: 'active',
                title: '복제 상태 조사',
                detail: 'replica 배치와 동기화 상태를 각각 조회합니다.',
                log: 'describe partition=orders-0',
              },
              {
                atMs: 400,
                kind: 'evidence.observed',
                component: 'replica',
                state: 'complete',
                title: '현재 ISR 증거 확보',
                detail: 'broker-3은 replica이지만 현재 ISR에는 포함되지 않습니다.',
                log: 'replicas=[1,2,3] isr=[1,2] out.of.sync=[3]',
              },
              {
                atMs: 800,
                kind: 'experiment.succeeded',
                component: 'broker',
                state: 'complete',
                title: '쓰기 조건을 현재 상태로 판단',
                detail: 'acks=all은 모든 현재 ISR의 ACK를 요구하며, min.insync.replicas가 최소 ISR 크기를 제한합니다.',
                log: 'current.isr.count=2 durability-margin=1',
              },
            ],
            diagnosis: null,
          },
        },
      ],
    },
    {
      id: 'min-isr-write-failure',
      title: 'acks=all 쓰기 거부',
      mission: 'min.insync.replicas가 부족한 쓰기를 거부해 durability를 보호하는 이유를 확인한다.',
      predictionPrompt: 'min.insync.replicas=2인데 ISR이 leader 한 대뿐이면 acks=all 요청은 어떻게 될까?',
      successCriteria: 'ISR을 복구한 뒤 acks=all 쓰기를 성공시킨다.',
      recommendedChoiceId: 'restore-isr-before-write',
      referenceIds: ['topic-configs', 'producer-configs'],
      choices: [
        {
          id: 'write-with-one-isr',
          label: 'ISR 1대로 그대로 쓴다',
          description: 'replication factor가 3이므로 leader 한 대만 살아 있어도 쓸 수 있다고 판단한다.',
          outcome: {
            status: 'failed',
            summary: 'acks=all 요청은 현재 ISR 1개가 min.insync.replicas=2를 만족하지 못해 거부됐습니다.',
            events: [
              {
                atMs: 0,
                kind: 'configuration.applied',
                component: 'broker',
                state: 'active',
                title: '내구성 조건 적용',
                detail: 'topic의 min.insync.replicas는 2이고 producer는 acks=all입니다.',
                log: 'min.insync.replicas=2 acks=all',
              },
              {
                atMs: 350,
                kind: 'record.dispatched',
                component: 'producer',
                state: 'active',
                title: '현재 ISR로 produce 시도',
                detail: 'leader만 ISR에 남은 상태에서 record를 보냅니다.',
                log: 'produce partition=orders-0 isr=[1]',
              },
              {
                atMs: 700,
                kind: 'experiment.failed',
                component: 'broker',
                state: 'failed',
                title: '최소 ISR 미달로 쓰기 거부',
                detail: '불충분한 복제 상태에서 성공을 반환하지 않아 데이터 내구성을 보호합니다.',
                log: 'error=NotEnoughReplicas isr.count=1 required=2',
              },
            ],
            diagnosis: {
              symptom: 'acks=all produce가 broker에서 거부됐습니다.',
              rootCause: '현재 ISR 수가 topic의 min.insync.replicas보다 작습니다.',
              evidence: ['acks=all', 'isr.count=1', 'min.insync.replicas=2', 'NotEnoughReplicas'],
              recommendedChoiceId: 'restore-isr-before-write',
              tradeOff: 'min.insync.replicas를 높이면 손실 위험은 낮아지지만 replica 장애 중 쓰기 가용성은 감소합니다.',
            },
          },
        },
        {
          id: 'restore-isr-before-write',
          label: 'ISR을 복구한 뒤 다시 쓴다',
          description: 'follower가 leader를 따라잡아 ISR이 2가 된 뒤 동일 record를 재전송한다.',
          outcome: {
            status: 'succeeded',
            summary: 'ISR이 최소 2대로 회복된 뒤 acks=all 쓰기가 안전하게 승인됐습니다.',
            events: [
              {
                atMs: 0,
                kind: 'state.changed',
                component: 'replica',
                state: 'active',
                title: 'follower 동기화',
                detail: 'broker-2가 leader의 끝 offset까지 따라잡습니다.',
                log: 'broker-2 fetch-offset=42 leader-end-offset=42',
              },
              {
                atMs: 400,
                kind: 'evidence.observed',
                component: 'replica',
                state: 'complete',
                title: '최소 ISR 회복',
                detail: '현재 ISR 2대가 min.insync.replicas=2를 충족합니다.',
                log: 'isr=[1,2] isr.count=2 required=2',
              },
              {
                atMs: 800,
                kind: 'experiment.succeeded',
                component: 'broker',
                state: 'complete',
                title: 'acks=all 쓰기 성공',
                detail: '현재 ISR 모두가 append를 확인한 뒤 ACK가 반환됩니다.',
                log: 'append offset=42 acked-by=[1,2] result=success',
              },
            ],
            diagnosis: null,
          },
        },
      ],
    },
    {
      id: 'leader-failover',
      title: 'leader 교체 후 복구',
      mission: 'leader 장애 중 쓰기 실패와 ISR 내부 새 leader 선출 후 재시도를 구분한다.',
      predictionPrompt: 'leader가 사라진 직후 같은 broker로 재시도하면 성공할까?',
      successCriteria: '새 leader와 ISR을 확인한 뒤 동일 입력을 재실행한다.',
      recommendedChoiceId: 'wait-for-isr-leader-and-retry',
      referenceIds: ['kafka-introduction', 'producer-configs'],
      choices: [
        {
          id: 'retry-before-election',
          label: '선출 확인 없이 즉시 재시도한다',
          description: '기존 leader가 계속 요청을 받을 것이라고 가정한다.',
          outcome: {
            status: 'failed',
            summary: '기존 leader 장애와 metadata 변경 사이에 재시도해 쓸 수 있는 leader를 찾지 못했습니다.',
            events: [
              {
                atMs: 0,
                kind: 'state.changed',
                component: 'broker',
                state: 'failed',
                title: '기존 leader 장애',
                detail: 'broker-1이 응답을 멈추고 partition leader가 일시적으로 비어 있습니다.',
                log: 'broker-1 down partition=orders-0 leader=none',
              },
              {
                atMs: 250,
                kind: 'record.dispatched',
                component: 'producer',
                state: 'blocked',
                title: '오래된 metadata로 재시도',
                detail: 'producer가 기존 leader 주소로 동일 record를 보냅니다.',
                log: 'metadata.leader=broker-1 retry=1',
              },
              {
                atMs: 500,
                kind: 'experiment.failed',
                component: 'producer',
                state: 'failed',
                title: 'leader 없음',
                detail: '새 leader 선출과 metadata 갱신 전에는 append 성공을 확인할 수 없습니다.',
                log: 'error=NotLeaderOrFollower append=not-confirmed',
              },
            ],
            diagnosis: {
              symptom: '장애 직후 재시도가 leader 오류로 실패했습니다.',
              rootCause: 'ISR 내부 새 leader 선출과 producer metadata 갱신을 확인하지 않았습니다.',
              evidence: ['old leader=broker-1 down', 'leader=none', 'NotLeaderOrFollower', 'append 미확인'],
              recommendedChoiceId: 'wait-for-isr-leader-and-retry',
              tradeOff: 'failover 확인은 재시도 지연을 늘리지만 성공하지 않은 append를 성공으로 오인하지 않게 합니다.',
            },
          },
        },
        {
          id: 'wait-for-isr-leader-and-retry',
          label: '새 leader와 ISR 확인 후 재시도한다',
          description: 'ISR 멤버가 새 leader로 선출되고 metadata가 갱신된 뒤 동일 입력을 보낸다.',
          outcome: {
            status: 'succeeded',
            summary: 'ISR 멤버 broker-2가 새 leader가 된 것을 확인하고 재시도해 append와 ACK를 확보했습니다.',
            events: [
              {
                atMs: 0,
                kind: 'state.changed',
                component: 'broker',
                state: 'active',
                title: 'ISR 내부 leader 선출',
                detail: '동기화되어 있던 broker-2가 새 leader가 됩니다.',
                log: 'partition=orders-0 leader=broker-2 isr=[2,3]',
              },
              {
                atMs: 400,
                kind: 'configuration.applied',
                component: 'producer',
                state: 'complete',
                title: 'producer metadata 갱신',
                detail: 'producer가 orders-0의 새 leader를 확인합니다.',
                log: 'metadata.refresh leader=broker-2 epoch=8',
              },
              {
                atMs: 800,
                kind: 'experiment.succeeded',
                component: 'broker',
                state: 'complete',
                title: '재시도 append와 ACK 확인',
                detail: '동일 record가 새 leader에 기록되고 현재 ISR의 확인 뒤 ACK가 돌아옵니다.',
                log: 'append offset=43 leader=broker-2 acked-by=[2,3]',
              },
            ],
            diagnosis: null,
          },
        },
      ],
    },
  ],
}
