import {
  runChapterRule,
  type ChapterEventTemplate,
  type ChapterRuleModule,
  type ChapterSimulationInput,
} from '../chapterSimulation'

const started = (detail: string): ChapterEventTemplate => ({
  atMs: 0,
  kind: 'experiment.started',
  component: 'producer',
  state: 'active',
  title: 'producer 장애 실험을 시작한다',
  detail,
  log: `[producer] ${detail}`,
})

export const chapter3Rule = {
  chapterId: 3,
  experiments: [
    {
      id: 'acks-leader-loss',
      title: 'ACK 직후 leader 장애',
      mission: 'acks 성공 조건이 leader 장애 뒤 record 내구성에 미치는 영향을 비교한다.',
      predictionPrompt: 'leader만 append한 직후 ACK를 보내고 leader가 사라지면 record는 남아 있을까?',
      successCriteria: 'acks=1과 acks=all의 성공 조건 및 latency/durability trade-off를 증거로 구분한다.',
      recommendedChoiceId: 'wait-for-isr-acks',
      referenceIds: ['producer-configs'],
      choices: [
        {
          id: 'leader-only-ack',
          label: 'acks=1로 즉시 확인',
          description: 'leader가 로컬 로그에 append하면 follower 복제를 기다리지 않고 성공 처리한다.',
          outcome: {
            status: 'failed',
            summary: 'leader ACK 뒤 follower 복제 전에 장애가 발생해 성공으로 본 record가 새 leader에 없었다.',
            events: [
              started('acks=1, replication.factor=3에서 배송 record 전송'),
              {
                atMs: 90,
                kind: 'configuration.applied',
                component: 'producer',
                state: 'complete',
                title: 'leader ACK 조건을 선택했다',
                detail: 'leader의 로컬 append만으로 요청이 성공한다.',
                log: '[config] acks=1',
              },
              {
                atMs: 180,
                kind: 'record.dispatched',
                component: 'broker',
                state: 'active',
                title: 'leader가 record를 append하고 ACK했다',
                detail: 'follower 복제는 아직 완료되지 않았지만 producer는 성공을 받았다.',
                log: '[leader-0] append offset=72; ack before follower replication',
              },
              {
                atMs: 270,
                kind: 'state.changed',
                component: 'replica',
                state: 'failed',
                title: 'leader가 복제 전에 중단됐다',
                detail: 'record가 없는 follower가 새 leader로 선출됐다.',
                log: '[cluster] leader-0 offline; leader-1 elected without offset=72',
              },
              {
                atMs: 360,
                kind: 'evidence.observed',
                component: 'broker',
                state: 'blocked',
                title: '성공 응답과 새 leader 로그가 불일치한다',
                detail: 'producer는 성공을 기록했지만 새 leader의 high watermark에 record가 없다.',
                log: '[evidence] producer=ACK; new-leader offset=72 absent',
              },
              {
                atMs: 450,
                kind: 'experiment.failed',
                component: 'application',
                state: 'failed',
                title: 'leader 단독 ACK의 내구성 한계를 확인했다',
                detail: '낮은 응답 지연과 follower 장애 내성 사이의 선택이 드러났다.',
                log: '[result] acknowledged record was not replicated',
              },
            ],
            diagnosis: {
              symptom: '성공 처리한 배송 record가 leader 교체 뒤 조회되지 않는다.',
              rootCause: 'acks=1이 follower 복제를 성공 조건에 포함하지 않아 복제 전 leader 손실 창이 생겼다.',
              evidence: ['leader-0만 offset=72 append', 'follower 복제 전 ACK', '새 leader에 offset=72 없음'],
              recommendedChoiceId: 'wait-for-isr-acks',
              tradeOff: 'acks=all은 더 강한 내구성을 제공하지만 ACK 대기 시간과 가용성 비용이 커질 수 있다.',
            },
          },
        },
        {
          id: 'wait-for-isr-acks',
          label: 'acks=all로 ISR 확인',
          description: 'leader가 모든 현재 ISR replica의 성공 조건을 충족한 뒤 ACK한다.',
          outcome: {
            status: 'succeeded',
            summary: '모든 현재 ISR에 record가 반영된 뒤 ACK해 leader 장애 후에도 새 leader에서 관찰됐다.',
            events: [
              started('acks=all, replication.factor=3, min.insync.replicas=2로 전송'),
              {
                atMs: 100,
                kind: 'configuration.applied',
                component: 'producer',
                state: 'complete',
                title: 'ISR 기반 ACK 조건을 적용했다',
                detail: 'acks=all은 현재 ISR replica들의 성공 조건을 기다린다.',
                log: '[config] acks=all; min.insync.replicas=2',
              },
              {
                atMs: 220,
                kind: 'record.dispatched',
                component: 'replica',
                state: 'active',
                title: '현재 ISR이 record를 복제했다',
                detail: 'leader-0과 follower-1이 offset 72를 반영한 뒤 ACK가 반환됐다.',
                log: '[isr] replicas=[0,1]; offset=72 replicated; ACK',
              },
              {
                atMs: 330,
                kind: 'state.changed',
                component: 'broker',
                state: 'active',
                title: 'leader 장애 뒤 follower가 승격됐다',
                detail: 'offset 72를 가진 ISR follower가 새 leader가 됐다.',
                log: '[cluster] leader-0 offline; leader-1 elected',
              },
              {
                atMs: 430,
                kind: 'evidence.observed',
                component: 'broker',
                state: 'complete',
                title: '새 leader에서 record를 확인했다',
                detail: 'ACK된 offset 72가 새 leader 로그에 남아 있다.',
                log: '[evidence] new-leader contains offset=72',
              },
              {
                atMs: 520,
                kind: 'experiment.succeeded',
                component: 'application',
                state: 'complete',
                title: 'ACK 강도를 내구성 요구에 맞췄다',
                detail: '더 긴 ACK 지연을 수용해 ISR 복제 증거를 성공 조건으로 삼았다.',
                log: '[result] replicated ACK survived leader loss',
              },
            ],
            diagnosis: null,
          },
        },
      ],
    },
    {
      id: 'retry-duplicate-order',
      title: '응답을 잃어버린 재시도',
      mission: '재시도가 손실을 줄이는 동시에 중복·재정렬 위험을 만들 수 있는 조건을 관찰한다.',
      predictionPrompt: '첫 요청의 응답만 유실되고 뒤 요청이 먼저 성공하면 단순 retry 결과는 어떻게 보일까?',
      successCriteria: 'delivery.timeout.ms의 시간 경계와 idempotence의 중복·순서 보호 역할을 구분한다.',
      recommendedChoiceId: 'idempotent-bounded-retry',
      referenceIds: ['producer-configs', 'kafka-producer-api'],
      choices: [
        {
          id: 'unbounded-non-idempotent-retry',
          label: 'idempotence 없이 동시 재시도',
          description: 'enable.idempotence=false, max.in.flight=5에서 응답 유실 요청을 다시 보낸다.',
          outcome: {
            status: 'failed',
            summary: '뒤 요청이 먼저 기록되고 ACK가 유실된 앞 요청이 재전송돼 중복과 재정렬 위험이 드러났다.',
            events: [
              started('record A와 B를 같은 partition에 연속 전송'),
              {
                atMs: 90,
                kind: 'configuration.applied',
                component: 'producer',
                state: 'complete',
                title: '비멱등 동시 요청을 허용했다',
                detail: 'enable.idempotence=false, max.in.flight.requests.per.connection=5다.',
                log: '[config] idempotence=false; max.in.flight=5; retries=MAX',
              },
              {
                atMs: 180,
                kind: 'record.dispatched',
                component: 'broker',
                state: 'active',
                title: 'A의 응답이 유실되고 B가 먼저 확인됐다',
                detail: 'broker는 A를 append했지만 ACK가 사라졌고, B 요청은 성공했다.',
                log: '[network] A appended@90 ACK lost; B appended@91 ACK received',
              },
              {
                atMs: 290,
                kind: 'state.changed',
                component: 'retry',
                state: 'active',
                title: 'producer가 A를 다시 전송했다',
                detail: 'broker가 이전 A와 재시도 A를 같은 record로 식별할 sequence 정보가 없다.',
                log: '[retry] A resent; appended@92',
              },
              {
                atMs: 400,
                kind: 'evidence.observed',
                component: 'partition',
                state: 'blocked',
                title: '로그에 A, B, A가 보인다',
                detail: 'retry 활성화만으로 exactly-once나 원래 전송 순서를 보장하지 않는다.',
                log: '[evidence] p0@90=A, p0@91=B, p0@92=A',
              },
              {
                atMs: 510,
                kind: 'experiment.failed',
                component: 'application',
                state: 'failed',
                title: '단순 retry의 중복 위험을 확인했다',
                detail: '재시도 전체 시간을 제한하는 것과 중복을 억제하는 것은 서로 다른 역할이다.',
                log: '[result] retry produced duplicate A after B',
              },
            ],
            diagnosis: {
              symptom: '한 partition에 A, B, A 순서로 중복 record가 남았다.',
              rootCause: 'idempotence 없이 여러 요청을 동시에 보내 ACK 유실 요청의 재시도를 broker가 중복으로 판별하지 못했다.',
              evidence: ['A@90 ACK 유실', 'B@91 성공', '재시도 A@92 append'],
              recommendedChoiceId: 'idempotent-bounded-retry',
              tradeOff: '재시도는 일시 장애 내성을 높이지만 delivery timeout 안에서 latency가 늘고, 비멱등 설정이면 중복·재정렬 위험이 남는다.',
            },
          },
        },
        {
          id: 'idempotent-bounded-retry',
          label: '멱등성과 delivery timeout 적용',
          description: 'enable.idempotence=true로 sequence를 사용하고 delivery.timeout.ms로 전체 전송 시간을 제한한다.',
          outcome: {
            status: 'succeeded',
            summary: 'broker가 재시도 A를 중복으로 제거하고 delivery timeout 안에서 A, B 순서를 유지했다.',
            events: [
              started('멱등 producer로 A와 B를 같은 partition에 전송'),
              {
                atMs: 90,
                kind: 'configuration.applied',
                component: 'producer',
                state: 'complete',
                title: '멱등성과 시간 예산을 적용했다',
                detail: 'acks=all, retries>0, max.in.flight≤5 조건과 delivery.timeout.ms=120000을 사용한다.',
                log: '[config] idempotence=true; acks=all; max.in.flight=5; delivery.timeout.ms=120000',
              },
              {
                atMs: 190,
                kind: 'record.dispatched',
                component: 'broker',
                state: 'active',
                title: 'A의 ACK가 유실됐다',
                detail: 'broker는 producer id와 sequence를 포함한 A를 이미 append했다.',
                log: '[broker] pid=7 seq=40 A appended@90; ACK lost',
              },
              {
                atMs: 300,
                kind: 'state.changed',
                component: 'retry',
                state: 'active',
                title: '같은 sequence로 A를 재시도했다',
                detail: 'broker가 재시도 record를 중복으로 인식하고 새 append 없이 성공 응답한다.',
                log: '[retry] pid=7 seq=40 deduplicated; seq=41 B appended@91',
              },
              {
                atMs: 410,
                kind: 'evidence.observed',
                component: 'partition',
                state: 'complete',
                title: '로그에 A와 B가 한 번씩 남았다',
                detail: '전송은 delivery timeout 시간 예산 안에서 완료됐다.',
                log: '[evidence] p0@90=A, p0@91=B; elapsed=410ms<120000ms',
              },
              {
                atMs: 510,
                kind: 'experiment.succeeded',
                component: 'application',
                state: 'complete',
                title: '중복 억제와 시간 제한을 구분해 적용했다',
                detail: 'idempotence는 producer session의 재시도 안전성을, delivery timeout은 완료 시간 상한을 담당한다.',
                log: '[result] retry deduplicated within delivery timeout',
              },
            ],
            diagnosis: null,
          },
        },
      ],
    },
    {
      id: 'idempotent-repair',
      title: 'idempotent producer 복구',
      mission: '멱등 producer의 필수 설정 조건을 충족하고 충돌 구성을 진단한다.',
      predictionPrompt: 'enable.idempotence=true인데 acks=1과 max.in.flight=6을 명시하면 안전하게 시작할까?',
      successCriteria: 'acks=all, retries>0, max.in.flight≤5의 일관된 멱등 설정으로 동일 장애를 재실행한다.',
      recommendedChoiceId: 'coherent-idempotent-config',
      referenceIds: ['producer-configs'],
      choices: [
        {
          id: 'conflicting-idempotent-config',
          label: '충돌 설정 강제',
          description: 'enable.idempotence=true와 함께 acks=1, retries=0, max.in.flight=6을 명시한다.',
          outcome: {
            status: 'failed',
            summary: '멱등성 필수 조건과 충돌하는 명시적 설정 때문에 producer 구성이 거부됐다.',
            events: [
              started('멱등성을 켠 채 충돌하는 전송 설정을 로드'),
              {
                atMs: 80,
                kind: 'configuration.applied',
                component: 'producer',
                state: 'blocked',
                title: '상호 모순된 설정이 발견됐다',
                detail: 'idempotence=true지만 acks=1, retries=0, max.in.flight=6이다.',
                log: '[config] enable.idempotence=true conflicts with acks/retries/max.in.flight',
              },
              {
                atMs: 160,
                kind: 'state.changed',
                component: 'producer',
                state: 'failed',
                title: 'producer 초기화가 중단됐다',
                detail: '명시적으로 활성화한 idempotence의 요구 조건을 충족하지 못했다.',
                log: '[producer] ConfigException: idempotence prerequisites violated',
              },
              {
                atMs: 240,
                kind: 'evidence.observed',
                component: 'retry',
                state: 'blocked',
                title: '재시도 실험까지 도달하지 못했다',
                detail: 'retries=0은 멱등 producer가 transient failure를 안전하게 재전송할 조건과 충돌한다.',
                log: '[evidence] zero records dispatched; producer creation failed',
              },
              {
                atMs: 320,
                kind: 'experiment.failed',
                component: 'application',
                state: 'failed',
                title: '설정 충돌을 진단했다',
                detail: 'Kafka 4.3의 기본 멱등성도 충돌 설정이 있으면 조용히 비활성화될 수 있으므로 명시적 검증이 필요하다.',
                log: '[result] incompatible idempotence configuration',
              },
            ],
            diagnosis: {
              symptom: 'producer가 시작되지 않아 record를 한 건도 보내지 못했다.',
              rootCause: 'enable.idempotence=true의 필수 조건인 acks=all, retries>0, max.in.flight≤5와 충돌했다.',
              evidence: ['acks=1', 'retries=0', 'max.in.flight=6', 'ConfigException before dispatch'],
              recommendedChoiceId: 'coherent-idempotent-config',
              tradeOff: '멱등성을 위한 제한은 일부 동시성 조정 자유도를 줄이지만 재시도 중복과 순서 역전 위험을 억제한다.',
            },
          },
        },
        {
          id: 'coherent-idempotent-config',
          label: '멱등 조건을 일관되게 적용',
          description: 'enable.idempotence=true, acks=all, retries>0, max.in.flight=5를 함께 사용한다.',
          outcome: {
            status: 'succeeded',
            summary: '일관된 멱등 설정으로 producer가 시작되고 응답 유실 재시도를 중복 없이 완료했다.',
            events: [
              started('멱등 producer 요구 조건을 한 묶음으로 적용'),
              {
                atMs: 80,
                kind: 'configuration.applied',
                component: 'producer',
                state: 'complete',
                title: '호환되는 설정이 검증됐다',
                detail: 'acks=all, retries>0, max.in.flight=5가 idempotence 조건을 만족한다.',
                log: '[config] idempotence=true; acks=all; retries=MAX; max.in.flight=5',
              },
              {
                atMs: 170,
                kind: 'record.dispatched',
                component: 'broker',
                state: 'active',
                title: 'sequence가 포함된 record를 전송했다',
                detail: 'producer id 9의 sequence 12가 leader와 ISR에 append됐다.',
                log: '[broker] pid=9 seq=12 appended@120; ACK lost',
              },
              {
                atMs: 270,
                kind: 'state.changed',
                component: 'retry',
                state: 'active',
                title: '동일 sequence 재시도가 제거됐다',
                detail: 'broker가 pid와 sequence를 사용해 이미 append한 요청임을 확인했다.',
                log: '[retry] pid=9 seq=12 recognized; no second append',
              },
              {
                atMs: 370,
                kind: 'evidence.observed',
                component: 'partition',
                state: 'complete',
                title: 'record가 정확히 한 번 append됐다',
                detail: 'partition 로그에는 sequence 12가 한 위치에만 존재한다.',
                log: '[evidence] p0@120 count(pid=9,seq=12)=1',
              },
              {
                atMs: 460,
                kind: 'experiment.succeeded',
                component: 'application',
                state: 'complete',
                title: '멱등 producer가 안전하게 복구됐다',
                detail: '이 보장은 producer session과 단일 partition 전송 범위이며 전체 애플리케이션 transaction과는 다르다.',
                log: '[result] coherent idempotent retry succeeded',
              },
            ],
            diagnosis: null,
          },
        },
      ],
    },
  ],
} satisfies ChapterRuleModule

export function runChapter3Rule(input: ChapterSimulationInput) {
  return runChapterRule(chapter3Rule, input)
}
