import type { ChapterRuleModule } from '../chapterSimulation'

export const chapter5Rule: ChapterRuleModule = {
  chapterId: 5,
  experiments: [
    {
      id: 'poll-versus-process',
      title: '가져오기와 처리 완료의 간격',
      mission: 'consumer position, 업무 처리 완료, committed offset을 서로 다른 상태로 추적한다.',
      predictionPrompt: 'poll 직후 처리 전에 장애가 나면 업무는 완료된 것일까?',
      successCriteria: 'poll과 처리 완료를 분리하고 처리 뒤 다음 offset을 commit한다.',
      recommendedChoiceId: 'process-then-commit',
      referenceIds: ['consumer-offset-tracking', 'consumer-configs'],
      choices: [
        {
          id: 'treat-poll-as-complete',
          label: 'poll을 처리 완료로 본다',
          description: 'record가 반환된 순간 업무와 재시작 위치가 모두 안전하다고 가정한다.',
          outcome: {
            status: 'failed',
            summary: 'poll은 consumer position을 전진시켰지만 업무 완료나 안전한 commit을 증명하지 못했습니다.',
            events: [
              {
                atMs: 0,
                kind: 'record.dispatched',
                component: 'consumer',
                state: 'active',
                title: 'offset 40 poll',
                detail: 'consumer가 offset 40 record를 가져오고 position은 41이 됩니다.',
                log: 'poll record.offset=40 consumer.position=41',
              },
              {
                atMs: 350,
                kind: 'state.changed',
                component: 'application',
                state: 'failed',
                title: '업무 처리 전 장애',
                detail: '주문 반영 전에 application이 중단됩니다.',
                log: 'business-effect=absent processed.offset=none',
              },
              {
                atMs: 700,
                kind: 'experiment.failed',
                component: 'offset',
                state: 'failed',
                title: '서로 다른 진행 상태를 혼동함',
                detail: 'position 41은 다음 fetch 위치이며 처리 완료 또는 committed offset과 같지 않습니다.',
                log: 'position=41 processed=none committed=40',
              },
            ],
            diagnosis: {
              symptom: 'poll한 record가 업무에 반영되지 않은 채 consumer가 중단됐습니다.',
              rootCause: 'poll로 이동한 consumer position을 업무 처리와 committed offset으로 오해했습니다.',
              evidence: ['record.offset=40', 'consumer.position=41', 'processed.offset=none', 'committed.offset=40'],
              recommendedChoiceId: 'process-then-commit',
              tradeOff: '처리 완료 뒤 commit하면 손실 위험은 줄지만 commit 전 장애 시 재처리가 발생할 수 있습니다.',
            },
          },
        },
        {
          id: 'process-then-commit',
          label: '처리 후 다음 offset을 commit한다',
          description: 'poll, 업무 처리, 다음에 읽을 offset commit을 순서대로 기록한다.',
          outcome: {
            status: 'succeeded',
            summary: 'offset 40을 처리한 뒤 다음에 읽을 위치 41을 commit했습니다.',
            events: [
              {
                atMs: 0,
                kind: 'record.dispatched',
                component: 'consumer',
                state: 'active',
                title: 'offset 40 poll',
                detail: 'record를 가져오고 position이 다음 위치로 이동합니다.',
                log: 'record.offset=40 consumer.position=41',
              },
              {
                atMs: 350,
                kind: 'evidence.observed',
                component: 'application',
                state: 'complete',
                title: '업무 처리 완료',
                detail: '주문 반영 성공을 별도 증거로 남깁니다.',
                log: 'business-effect=applied processed.offset=40',
              },
              {
                atMs: 700,
                kind: 'experiment.succeeded',
                component: 'offset',
                state: 'complete',
                title: '다음 offset commit',
                detail: '완료한 40 다음의 위치인 41을 재시작 지점으로 저장합니다.',
                log: 'commit.offset=41 meaning=next-record-to-read',
              },
            ],
            diagnosis: null,
          },
        },
      ],
    },
    {
      id: 'early-commit-loss',
      title: '너무 이른 commit',
      mission: '업무 처리 전에 offset을 commit할 때 발생하는 건너뛰기를 관찰한다.',
      predictionPrompt: 'offset 51을 먼저 commit하고 offset 50 처리 전에 장애가 나면 재시작 위치는 어디일까?',
      successCriteria: '업무 처리 성공 뒤 다음 offset을 commit해 건너뛰기를 막는다.',
      recommendedChoiceId: 'commit-after-processing',
      referenceIds: ['consumer-offset-tracking', 'consumer-configs'],
      choices: [
        {
          id: 'commit-before-processing',
          label: '처리 전에 commit한다',
          description: 'poll한 offset 50의 다음 위치 51을 먼저 commit한다.',
          outcome: {
            status: 'failed',
            summary: '처리되지 않은 offset 50보다 앞선 재시작 위치 51이 저장되어 업무를 건너뛰었습니다.',
            events: [
              {
                atMs: 0,
                kind: 'configuration.applied',
                component: 'offset',
                state: 'active',
                title: '조기 commit',
                detail: 'offset 50의 업무 처리 전에 다음 위치 51을 commit합니다.',
                log: 'record.offset=50 commit.offset=51 processed=false',
              },
              {
                atMs: 300,
                kind: 'state.changed',
                component: 'application',
                state: 'failed',
                title: '처리 전 consumer 장애',
                detail: '주문 반영 없이 consumer가 재시작됩니다.',
                log: 'consumer-crash business-effect=absent',
              },
              {
                atMs: 600,
                kind: 'experiment.failed',
                component: 'consumer',
                state: 'failed',
                title: 'offset 50 건너뜀',
                detail: '재시작은 committed offset 51부터 진행하므로 미처리 record 50을 다시 읽지 않습니다.',
                log: 'restart.position=51 skipped.offset=50 data-loss=risk',
              },
            ],
            diagnosis: {
              symptom: 'offset 50의 업무 효과가 없는데 재시작 후 다시 전달되지 않았습니다.',
              rootCause: '처리 완료 전에 다음 offset을 commit해 재시작 위치가 실제 업무 진행보다 앞섰습니다.',
              evidence: ['processed.offset=none', 'committed.offset=51', 'restart.position=51', 'skipped.offset=50'],
              recommendedChoiceId: 'commit-after-processing',
              tradeOff: '일찍 commit하면 재전달은 줄지만 처리되지 않은 업무를 영구히 건너뛸 위험이 있습니다.',
            },
          },
        },
        {
          id: 'commit-after-processing',
          label: '처리 완료 뒤 commit한다',
          description: 'offset 50의 업무 성공을 확인하고 다음 위치 51을 commit한다.',
          outcome: {
            status: 'succeeded',
            summary: '업무 증거를 먼저 확보하고 다음 위치를 commit해 미처리 record 건너뛰기를 막았습니다.',
            events: [
              {
                atMs: 0,
                kind: 'record.dispatched',
                component: 'consumer',
                state: 'active',
                title: 'offset 50 수신',
                detail: 'record를 poll했지만 아직 commit하지 않습니다.',
                log: 'record.offset=50 commit.pending=true',
              },
              {
                atMs: 350,
                kind: 'evidence.observed',
                component: 'application',
                state: 'complete',
                title: 'offset 50 처리 완료',
                detail: '업무 저장소가 주문 반영 성공을 확인합니다.',
                log: 'processed.offset=50 business-effect=applied',
              },
              {
                atMs: 700,
                kind: 'experiment.succeeded',
                component: 'offset',
                state: 'complete',
                title: 'offset 51 commit',
                detail: '다음에 읽을 위치 51을 처리 경계 뒤에서 저장합니다.',
                log: 'commit.offset=51 after=processed.offset:50',
              },
            ],
            diagnosis: null,
          },
        },
      ],
    },
    {
      id: 'late-commit-replay',
      title: '늦은 commit과 재처리',
      mission: '처리 후 commit 전 장애가 만드는 재전달과 멱등 처리의 역할을 확인한다.',
      predictionPrompt: '업무는 완료됐지만 offset commit 전에 장애가 나면 offset 70은 다시 올까?',
      successCriteria: '재전달을 예상하고 멱등하게 처리한 뒤 다음 offset을 commit한다.',
      recommendedChoiceId: 'idempotent-replay-then-commit',
      referenceIds: ['consumer-offset-tracking'],
      choices: [
        {
          id: 'assume-no-replay-after-processing',
          label: '처리했으니 재전달되지 않는다고 본다',
          description: '업무 완료 자체가 Kafka의 committed offset도 이동시킨다고 가정한다.',
          outcome: {
            status: 'failed',
            summary: '업무는 완료됐지만 committed offset이 남아 있어 offset 70이 재전달되고 효과가 중복됐습니다.',
            events: [
              {
                atMs: 0,
                kind: 'evidence.observed',
                component: 'application',
                state: 'complete',
                title: 'offset 70 업무 처리 완료',
                detail: '결제가 반영됐지만 아직 다음 위치 71을 commit하지 않았습니다.',
                log: 'processed.offset=70 payment.count=1 committed.offset=70',
              },
              {
                atMs: 300,
                kind: 'state.changed',
                component: 'consumer',
                state: 'failed',
                title: 'commit 전 장애와 재시작',
                detail: 'consumer는 마지막 committed offset 70으로 돌아갑니다.',
                log: 'consumer-crash restart.position=70',
              },
              {
                atMs: 600,
                kind: 'experiment.failed',
                component: 'application',
                state: 'failed',
                title: '비멱등 업무 중복',
                detail: 'offset 70을 다시 처리해 같은 결제가 두 번 반영됩니다.',
                log: 'replayed.offset=70 payment.count=2 duplicate=true',
              },
            ],
            diagnosis: {
              symptom: '처리 완료된 offset 70이 재전달되어 업무 효과가 중복됐습니다.',
              rootCause: '처리 완료와 Kafka offset commit이 원자적이지 않은데 재전달을 고려하지 않았습니다.',
              evidence: ['processed.offset=70', 'committed.offset=70', 'restart.position=70', 'duplicate effect count=2'],
              recommendedChoiceId: 'idempotent-replay-then-commit',
              tradeOff: '늦은 commit은 미처리 손실을 피하지만 재전달을 허용하므로 멱등성이나 중복 제거 비용이 필요합니다.',
            },
          },
        },
        {
          id: 'idempotent-replay-then-commit',
          label: '재전달을 멱등 처리하고 commit한다',
          description: '업무 키로 중복 효과를 차단하고 offset 70 다음 위치를 commit한다.',
          outcome: {
            status: 'succeeded',
            summary: 'offset 70 재전달을 감지해 업무 효과를 한 번만 유지하고 offset 71을 commit했습니다.',
            events: [
              {
                atMs: 0,
                kind: 'record.dispatched',
                component: 'consumer',
                state: 'active',
                title: 'offset 70 재전달',
                detail: '마지막 committed offset에서 같은 record가 다시 전달됩니다.',
                log: 'restart.position=70 replayed.offset=70',
              },
              {
                atMs: 350,
                kind: 'evidence.observed',
                component: 'application',
                state: 'complete',
                title: '멱등 키로 중복 효과 차단',
                detail: '이미 처리한 event id를 확인해 결제를 다시 적용하지 않습니다.',
                log: 'event.id=payment-70 already-processed=true payment.count=1',
              },
              {
                atMs: 700,
                kind: 'experiment.succeeded',
                component: 'offset',
                state: 'complete',
                title: '다음 offset commit',
                detail: '재처리 확인 뒤 다음에 읽을 위치 71을 저장합니다.',
                log: 'commit.offset=71 duplicate-effect=false',
              },
            ],
            diagnosis: null,
          },
        },
      ],
    },
  ],
}
